### ISSUE TITLE
ReadMe console.log forEach

### ISSUE THREAD

**Issue by davidchase** [bevacqua/but#3]
Shouldn't `n.forEach(but(console.log))` be `n.forEach(but(console.log.bind(console)))` ?
because otherwise it throws a TypeError

**Comment by bevacqua** [comment]
Right. Because Chrome

**Comment by davidchase** [comment]
I have the same issue in firefox and safari?

**Comment by bevacqua** [comment]
Yeah, I only ran actually used `but` in `node`, but I'll update the examples
